### PR TITLE
Milestone two of project 3 with bootstrap

### PR DESCRIPTION
**Pull request by samroodali**
Project 3 milestone responsive sections using bootstrap
it is responsive on all three screen sizes

### CODE REVIEW

**Review by smcommits — COMMENTED** [review]
# Status: Invalid :stop_sign:

## Friendly reminder: You should make sure that all the linter checks are passing before requesting a review.  You have failing linter checks.  This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you have fixed the linter errors!

# 
Any questions? Please reach out to me on [slack](https://microverse-students.slack.com/team/U017N7LLZ40)

**Comment by samroodali** [comment]
Thank you for the code review
we have reworked the entire project
we have responsive bootstrap columns

**Review by mahmoud717 — CHANGES_REQUESTED** [review]
### Changes required ♻️ 

**Hello @SamroodAli  & @Leon-Mbegera**

Great job with the project so far it looks amazing, but there are still some changes to be made:
 
---
### Requested 🔴 

- [ ] the order of the sections in the mobile view should be as follows: 
      
assdfg

- [ ] you should make sure to use more bootstrap classes in your css code.


### Optional 🟢 

- [ ] adding a little bit of styling to the signup form would be nice.

 

---

please make these changes and request another code review.

if you have any questions don't hesitate to contact me on slack **MahmoudMohammad**

**Comment by samroodali** [comment]
We fixed the order in mobile using bootstrap classes
we also fixed the logo on the sign up
thank you for the code review
feel free to reach out to us

**Review by arslanbisharat — APPROVED** [review]
Status: Approved 🟢
Congratulations team 🎉
This project has passed all the mandatory requirements. It is therefore approved ✔️

Do not forget to fill the project completion form.
Good luck with your next task.

**Pull request closed without merging**
