### PR TITLE
Milestone one to master

### PR DESCRIPTION
**Pull request by samroodali**
We learned the bootstrap grid today and applied the grid system to the project
we got the skeleton ready for the headers and footers
it is responsive for the three-screen sizes

### CODE REVIEW

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello team, great job working on this project so far.

1. Organized code.
2. Semantic HTML tags.
3. Good and mostly correct use of the Bootstrap class names.
4. Git Flow Guidelines followed correctly (merging to main branch)
5. Good PR summary
6. Descriptive and short commit messages.

Well done. However, there are still a few more changes to make in order to move on to the next.

<hr>

## **README**

- [x] Your readme file isn't complete, give yourself a reminder on how to build a great readme file [here](https://microverse.zendesk.com/hc/en-us/articles/360055660814-Professional-GitHub-repository)

- [x] Live demo link isn't working, please attach a valid working live demo link.
- [x] There's a broken image (Screenshot) please fix that.

## **Header**

- [x] Login and Subscribe buttons should have links. Please make that.
- [x] In mobile, the Login button changes into an icon. Kindly fix that.
- [x] The main menu has a form with the search bar.
- [x] In mobile and tablet the menu hides and shows a hamburger button. I cannot see the hamburger button.
- [x] The size of the elements change in desktop, tablet, and mobile. Please make that done.

## **General**

- [x] (Whole page) Some of the elements aren't aligned and/or styled the way they're on the original page. Please fix that issue.

<hr>

Please do the required changes, then request another review. 😊🙏
Good luck and happy coding. 👨‍💻💻

<hr>

Please feel free to reach me on Slack with the name "Mahmoud Bakr" if you have any questions regarding the above changes 🤗🙏

**Comment by mimipeshy** [comment]
### STATUS: CHANGES REQUESTED 🔴 ♻️ 
Hello team @SamroodAli and @Leon-Mbegera 👋🏾 👋🏾 , great job so far in this milestone. Your project looks almost similar to the original page, keep it up 😄 
However, few changes need to be made before the project can be approved

- [x]  Login and Subscribe buttons should have links. Please make that. Wrap these buttons with an `a` tag
- [x] Login text should be capitalized 😄 
- [x] In your CSS file get rid of `!important`. Using the !important rule is often considered a bad practice due to the clutter it can bring with one of CSS’s core mechanisms which are specificity. You can read more on this [here](https://www.google.com/amp/s/speckyboy.com/good-bad-css-practices/amp/)


That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name and I will be glad to help_
Regards
Peris Ndanu

**Comment by samroodali** [comment]
Fixed the buttons not having the links
removed !important in our css
capitalised Login

**Review by MuriloRoque — APPROVED** [review]
## Status: Approved :green_circle: 

### Hello @SamroodAli and @Leon-Mbegera :wave: 

### Thank you for making all of the requested changes. Your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[Twitter Follow](https://twitter.com/MuriloRoquePai1)

**Pull request merged**
